name: Build

on:
  workflow_dispatch:
    inputs:
      pre_release:
        description: "Publish pre-release"
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup NDK
        uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779
        id: setup-ndk
        with:
          add-to-path: false
          ndk-version: r27

      - name: Build
        run: |
          echo libxivpn commit: $(git rev-parse HEAD)
          ./build.sh all patch
          mkdir -p ../app/src/main/jniLibs/arm64-v8a
          mkdir -p ../app/src/main/jniLibs/x86_64
          mkdir -p ../app/src/main/jniLibs/armeabi-v7a
          cp libxivpn_x86_64.so ./../app/src/main/jniLibs/x86_64/libxivpn.so
          cp libxivpn_arm64.so ./../app/src/main/jniLibs/arm64-v8a/libxivpn.so
          cp libxivpn_armv7a.so ./../app/src/main/jniLibs/armeabi-v7a/libxivpn.so
        working-directory: ./libxivpn
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          mkdir ./sign
          echo $ENCODED_STRING > sign/keystore-b64.txt
          base64 -d ./sign/keystore-b64.txt > sign/keystore.jks

      - name: Build APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Rename and calculate sha256
        run: |
          cp ./app/build/outputs/apk/arm64_v8a/release/{app-arm64_v8a-release.apk,xivpn-arm64_v8a.apk}
          cp ./app/build/outputs/apk/universal/release/{app-universal-release.apk,xivpn-universal.apk}
          cp ./app/build/outputs/apk/x86_64/release/{app-x86_64-release.apk,xivpn-x86_64.apk}
          cp ./app/build/outputs/apk/armabi_v7a/release/{app-armabi_v7a-release.apk,xivpn-armeabi-v7a.apk}
          
          sha256sum ./app/build/outputs/apk/arm64_v8a/release/xivpn-arm64_v8a.apk > sha256.txt
          sha256sum ./app/build/outputs/apk/universal/release/xivpn-universal.apk >> sha256.txt
          sha256sum ./app/build/outputs/apk/x86_64/release/xivpn-x86_64.apk >> sha256.txt
          sha256sum ./app/build/outputs/apk/armabi_v7a/release/xivpn-armeabi-v7a.apk >> sha256.txt
          
          sha256sum ./libxivpn/libxivpn_x86_64.so >> sha256.txt
          sha256sum ./libxivpn/libxivpn_arm64.so >> sha256.txt
          sha256sum ./libxivpn/libxivpn_armv7a.so >> sha256.txt

      - name: Upload Universal APK to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./app/build/outputs/apk/universal/release/xivpn-universal.apk
          archive: false

      - name: Upload arm64 APK to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./app/build/outputs/apk/arm64_v8a/release/xivpn-arm64_v8a.apk
          archive: false

      - name: Upload armeabi-v7a APK to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./app/build/outputs/apk/armabi_v7a/release/xivpn-armeabi-v7a.apk
          archive: false

      - name: Upload x86_64 APK to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./app/build/outputs/apk/x86_64/release/xivpn-x86_64.apk
          archive: false

      - name: Upload arm64 libxivpn to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./libxivpn/libxivpn_arm64.so
          archive: false

      - name: Upload x86_64 libxivpn to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./libxivpn/libxivpn_x86_64.so
          archive: false

      - name: Upload mapping to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./app/build/outputs/mapping/arm64_v8aRelease/mapping.txt
          archive: false

      - name: Upload SHA256 to Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: sha256.txt
          archive: false

      - name: Copy APKs
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp ./app/build/outputs/apk/universal/release/app-universal-release.apk ./xivpn-universal.apk
          cp ./app/build/outputs/apk/x86_64/release/app-x86_64-release.apk ./xivpn-x86_64.apk
          cp ./app/build/outputs/apk/arm64_v8a/release/app-arm64_v8a-release.apk ./xivpn-arm64_v8a.apk
          cp ./app/build/outputs/apk/armabi_v7a/release/app-armabi_v7a-release.apk ./xivpn-armeabi-v7a.apk

      - name: GitHub Script
        if: inputs.pre_release
        uses: actions/github-script@v9.0.0
        with:
          script: |
            const now = new Date();
            const tag = now.getFullYear().toString()
              + String(now.getMonth() + 1).padStart(2, '0')
              + String(now.getDate()).padStart(2, '0')
              + String(now.getHours()).padStart(2, '0')
              + String(now.getMinutes()).padStart(2, '0')
              + String(now.getSeconds()).padStart(2, '0');
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            })


      - name: Prerelease
        if: inputs.pre_release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          files: |
            xivpn-universal.apk
            xivpn-x86_64.apk
            xivpn-arm64_v8a.apk
            xivpn-armeabi-v7a.apk
            sha256.txt

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          files: |
            xivpn-universal.apk
            xivpn-x86_64.apk
            xivpn-arm64_v8a.apk
            xivpn-armeabi-v7a.apk
            sha256.txt